[package]
name = "nostr-gt-client"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
secp256k1 = { version = "0.28.1", features = ["rand-std", "hashes"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.111"
anyhow = "1.0.79"
